name: CS5228
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.7.22=hf0a4a13_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - ipykernel=6.25.2=pyh1050b4e_0
  - ipython=8.16.1=pyh31c8845_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.4.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hca03da5_0
  - libcxx=16.0.6=h4653b0c_0
  - libffi=3.4.4=hca03da5_0
  - libsodium=1.0.18=h27ca646_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.1.3=h53f4e23_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3=py310hca03da5_0
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.10.13=hb885b13_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - pyzmq=25.1.0=py310h313beb8_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.0.0=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tornado=6.3.3=py310h80987f9_0
  - traitlets=5.11.2=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.8=pyhd8ed1ab_0
  - wheel=0.41.2=py310hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - attrs==23.1.0
      - category-encoders==2.6.3
      - certifi==2023.7.22
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - fiona==1.9.5
      - fonttools==4.43.1
      - geopandas==0.14.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.0
      - networkx==3.2.1
      - numpy==1.26.1
      - pandas==2.1.1
      - patsy==0.5.3
      - pillow==10.1.0
      - pyparsing==3.1.1
      - pyproj==3.6.1
      - pytz==2023.3.post1
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - shapely==2.0.2
      - statsmodels==0.14.0
      - threadpoolctl==3.2.0
      - tzdata==2023.3
      - xgboost==2.0.1
prefix: /Users/brandonng/anaconda3/envs/CS5228
